name: 发布和部署
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    name: 发布和部署
    runs-on: ubuntu-latest
    steps:

    - name: 拉取项目
      uses: actions/checkout@master
    - name: 打包构建
      uses: actions/setup-node@master
      with:
        node-version: '12.x'

    - name: 安装依赖
      run: npm install
    - name: 构建
      run: npm run dev
    